name: Release Latest

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.10.x'

      - name: Install dependencies
        run: npm install

      - name: Determine next version
        id: version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Last version: $LAST_TAG"
          VERSION=$(echo $LAST_TAG | awk -F. '{print $1"."$2"."$3+1}')
          echo "New version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update package.json version
        run: npm version $VERSION --no-git-tag-version

      - name: Commit version bump
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add package.json
          git commit -m "Bump version to $VERSION"
          git tag $VERSION
          git push origin main --tags

      - name: Build project
        run: npm run dist:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
          tag_name: latest-v0.1.0
          name: Release latest-v0.1.0
          body: "Automated release of version ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
