name: Release Latest

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.10.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run dist:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
          
          tag_name: latest-v0.1.0
          name: Release latest-v0.1.0
          body: "Automated release of version ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
